name: Docker Image CI

on:
 push:
   branches: 
     - master
     - develop
     - release/*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file .\Realtime.Api\Dockerfile --tag docker.pkg.github.com/rodolphocastro/ardc-realtime-api:$(date +%s)
