name: Docker Image CI

on: 
  push:
    branches: 
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -f ./Realtime.Api/Dockerfile -t ardc-realtime-api:latest -t docker.pkg.github.com/rodolphocastro/ardc.realtime.backend/realtime-api:latest .

